### ISSUE TITLE
No valid mtDNA contigs

### ISSUE THREAD

**Issue by SaelinB** [genepi/mtdna-server-2#24]
Hello, 

I'm trying to use mitoverse to assess variants in a plastid genome. It's a pretty unusual genome in that it is fragmented into small contigs. I've aligned the reads with bowtie, done samtools sort, but when I input the bam file I get an error: "No valid mtDNA contigs with length 16569 have been detected in your input files.".  I'm not sure where 16569 comes from. Would there be an issue with the validation step, given that these contigs are quite short (2-7kb)?

When I try Mutect2 on command line I get a similar error, here are the last few lines:

17:20:47.796 INFO Mutect2 - Done initializing engine
17:20:47.804 INFO NativeLibraryLoader - Loading libgkl_utils.so from jar:file:/home/student.unimelb.edu.au/sbjornson/opt/gatk-4.5.0.0/gatk-package-4.5.0.0-local.jar!/com/intel/gkl/native/libgkl_utils.so
17:20:47.805 DEBUG NativeLibraryLoader - Extracting libgkl_utils.so to /tmp/libgkl_utils11680565586657879505.so
17:20:47.805 INFO NativeLibraryLoader - Loading libgkl_smithwaterman.so from jar:file:/home/student.unimelb.edu.au/sbjornson/opt/gatk-4.5.0.0/gatk-package-4.5.0.0-local.jar!/com/intel/gkl/native/libgkl_smithwaterman.so
17:20:47.807 DEBUG NativeLibraryLoader - Extracting libgkl_smithwaterman.so to /tmp/libgkl_smithwaterman14591529823878817490.so
17:20:47.808 INFO SmithWatermanAligner - Using AVX accelerated SmithWaterman implementation
17:20:47.819 INFO NativeLibraryLoader - Loading libgkl_pairhmm_omp.so from jar:file:/home/student.unimelb.edu.au/sbjornson/opt/gatk-4.5.0.0/gatk-package-4.5.0.0-local.jar!/com/intel/gkl/native/libgkl_pairhmm_omp.so
17:20:47.832 DEBUG NativeLibraryLoader - Extracting libgkl_pairhmm_omp.so to /tmp/libgkl_pairhmm_omp15750479878658989455.so
17:20:47.832 INFO IntelPairHmm - Flush-to-zero (FTZ) is enabled when running PairHMM
17:20:47.832 INFO IntelPairHmm - Available threads: 32
17:20:47.832 INFO IntelPairHmm - Requested threads: 4
17:20:47.832 INFO PairHMM - Using the OpenMP multi-threaded AVX-accelerated native PairHMM implementation
17:20:47.833 INFO Mutect2 - Shutting down engine
[5 June 2024 at 5:20:47 pm AEST] org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2 done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=285212672
java.lang.IllegalArgumentException: samples cannot be empty
at org.broadinstitute.hellbender.utils.Utils.validateArg(Utils.java:798)
 at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.ReferenceConfidenceModel.<init>(ReferenceConfidenceModel.java:148)
 at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticReferenceConfidenceModel.<init>(SomaticReferenceConfidenceModel.java:39)
 at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2Engine.<init>(Mutect2Engine.java:171)
 at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2.onTraversalStart(Mutect2.java:265)
 at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1096)
 at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:149)
 at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:198)
 at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:217)
 at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:166)
 at org.broadinstitute.hellbender.Main.mainEntry(Main.java:209)
 at org.broadinstitute.hellbender.Main.main(Main.java:306)

Thanks for your help, 

Saelin

**Comment by seppinho** [comment]
Hi, the server/tool only accepts sequence reads from the human mitochrondrial genome (mapped against the rCRS with length 16,569 bp). Therefore you get this message. Hope this helps.

Sebastian
